<?php
/**
 * Plugin Name: Kecktech default site logo
 * Description: Bundled logos (header + footer white wordmark), custom logo, site icon, Astra/block fallbacks.
 * Version: 1.9.0
 */

if (!defined('ABSPATH')) {
    exit;
}

/** Must match the file mounted at wp-content/uploads/kecktech-branding/ */
const KECKTECH_BRAND_BASENAME = 'transparent-logo.png';

/** White-on-transparent wordmark for dark footers (optional mount; generated by scripts/apply-logo-transparency.py). */
const KECKTECH_FOOTER_BRAND_BASENAME = 'transparent-logo-white.png';

/**
 * Bump when bundled artwork changes so existing sites re-apply from the mount.
 * v1 = legacy (colored-logo.png); v2 = RGB transparent-logo.png; v3 = true RGBA (alpha) asset.
 */
const KECKTECH_LOGO_BRAND_VERSION = 3;

/**
 * @return string Absolute path to read-only bundled logo in container mount.
 */
function kecktech_brand_source_path(): string
{
    return WP_CONTENT_DIR . '/uploads/kecktech-branding/' . KECKTECH_BRAND_BASENAME;
}

/**
 * @return string Read-only footer wordmark on the branding volume.
 */
function kecktech_footer_brand_source_path(): string
{
    return WP_CONTENT_DIR . '/uploads/kecktech-branding/' . KECKTECH_FOOTER_BRAND_BASENAME;
}

/**
 * Copy footer wordmark into writable uploads (runs even when main logo bootstrap short-circuits).
 */
function kecktech_sync_footer_white_from_mount(): void
{
    $src = kecktech_footer_brand_source_path();
    if (!file_exists($src) || filesize($src) === 0) {
        return;
    }
    $upload_dir = wp_upload_dir();
    if (!empty($upload_dir['error'])) {
        return;
    }
    $destDir = trailingslashit($upload_dir['basedir']) . 'kecktech';
    if (!wp_mkdir_p($destDir)) {
        return;
    }
    $dest = $destDir . '/' . KECKTECH_FOOTER_BRAND_BASENAME;
    if (!file_exists($dest) || filesize($dest) === 0 || @filemtime($src) > @filemtime($dest)) {
        @copy($src, $dest);
    }
}

add_action('init', 'kecktech_sync_footer_white_from_mount', 4);

/**
 * Load admin media helpers on the front end (needed for wp_insert_attachment).
 */
function kecktech_load_media_libs(): void
{
    if (!function_exists('wp_insert_attachment')) {
        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/media.php';
        require_once ABSPATH . 'wp-admin/includes/image.php';
    }
}

/**
 * One-time cleanup when brand version in code is newer than the DB (e.g. colored → transparent).
 */
function kecktech_migrate_logo_brand_if_needed(): void
{
    $version = (int) get_option('kecktech_logo_brand_version', 0);
    if ($version >= KECKTECH_LOGO_BRAND_VERSION) {
        return;
    }

    $old_id = (int) get_option('kecktech_logo_attachment_id', 0);

    if ($old_id > 0 && (int) get_option('site_icon', 0) === $old_id) {
        delete_option('site_icon');
    }

    delete_option('kecktech_logo_attachment_id');
    delete_option('kecktech_logo_source_basename');
    remove_theme_mod('custom_logo');
}

/**
 * Mark branding migration complete only after logo + icon are in place.
 */
function kecktech_logo_mark_brand_current(): void
{
    update_option('kecktech_logo_brand_version', KECKTECH_LOGO_BRAND_VERSION, false);
}

/**
 * Copy bundled logo into writable uploads, register attachment, set custom_logo + site_icon.
 */
function kecktech_bootstrap_site_logo(): void
{
    $src = kecktech_brand_source_path();
    if (!file_exists($src)) {
        return;
    }

    kecktech_migrate_logo_brand_if_needed();

    $existing = (int) get_option('kecktech_logo_attachment_id', 0);
    if ($existing > 0 && get_post($existing) && wp_attachment_is_image($existing)) {
        $existingFile = get_attached_file($existing);
        if ($existingFile && file_exists($existingFile) && basename($existingFile) === KECKTECH_BRAND_BASENAME) {
            set_theme_mod('custom_logo', $existing);
            update_option('site_icon', $existing, true);
            kecktech_logo_mark_brand_current();
            return;
        }

        // Tracked attachment exists, but it's not the bundled branding file (or file is missing).
        delete_option('kecktech_logo_attachment_id');
        if ((int) get_option('site_icon', 0) === $existing) {
            delete_option('site_icon');
        }
    }

    // If the theme already has a custom logo, only keep it if it matches the bundled filename.
    $customLogo = get_theme_mod('custom_logo');
    if (!empty($customLogo)) {
        $customLogoId = (int) $customLogo;
        if ($customLogoId > 0) {
            $customFile = get_attached_file($customLogoId);
            if ($customFile && file_exists($customFile) && basename($customFile) === KECKTECH_BRAND_BASENAME) {
                update_option('kecktech_logo_attachment_id', $customLogoId, false);
                set_theme_mod('custom_logo', $customLogoId);
                update_option('site_icon', $customLogoId, true);
                kecktech_logo_mark_brand_current();
                return;
            }

            // Existing custom logo points somewhere else (e.g. legacy colored logo) or file is missing.
            remove_theme_mod('custom_logo');
            if ((int) get_option('site_icon', 0) === $customLogoId) {
                delete_option('site_icon');
            }
        }
    }

    kecktech_load_media_libs();

    $upload_dir = wp_upload_dir();
    if (!empty($upload_dir['error'])) {
        return;
    }

    $subdir  = 'kecktech';
    $destDir = trailingslashit($upload_dir['basedir']) . $subdir;
    if (!wp_mkdir_p($destDir)) {
        return;
    }

    $destFile = $destDir . '/' . KECKTECH_BRAND_BASENAME;
    // Repair “thumbnails only” state: WP can leave -150x150 etc. while the full file is missing → 404 in header.
    if (!file_exists($destFile) || filesize($destFile) === 0) {
        if (!@copy($src, $destFile)) {
            return;
        }
    } elseif (file_exists($src) && filesize($src) > 0 && filesize($src) !== (int) filesize($destFile)) {
        // Source updated (e.g. new transparent asset); refresh full file so URLs and metadata stay valid.
        if (@filemtime($src) > @filemtime($destFile)) {
            @copy($src, $destFile);
        }
    }

    $filetype = wp_check_filetype(basename($destFile), null);
    $attachment = array(
        'post_mime_type' => $filetype['type'] ?: 'image/png',
        'post_title'     => 'Kecktech logo',
        'post_content'   => '',
        'post_status'    => 'inherit',
    );

    $attach_id = wp_insert_attachment($attachment, $destFile);
    if (is_wp_error($attach_id) || !$attach_id) {
        return;
    }

    $meta = wp_generate_attachment_metadata($attach_id, $destFile);
    if (is_array($meta)) {
        wp_update_attachment_metadata($attach_id, $meta);
    }

    update_option('kecktech_logo_attachment_id', $attach_id, false);
    set_theme_mod('custom_logo', $attach_id);
    update_option('site_icon', $attach_id, true);
    kecktech_logo_mark_brand_current();
}
add_action('init', 'kecktech_bootstrap_site_logo', 5);

// ── HTTPS for uploads (broken http:// URLs → mixed content / empty img behind Traefik) ────────

/**
 * @param string|false $url
 */
function kecktech_force_https_url($url)
{
    if (is_string($url) && str_starts_with($url, 'http://')) {
        return 'https://' . substr($url, 7);
    }
    return $url;
}

/**
 * Canonical full-size file path (bootstrap copies the mount here).
 */
function kecktech_branding_file_path(): string
{
    return WP_CONTENT_DIR . '/uploads/kecktech/' . KECKTECH_BRAND_BASENAME;
}

/**
 * When the full PNG is missing (only WP thumbnails left, or failed copy), use the largest existing file
 * so the browser never requests a 404 — broken loads often show as a small solid “box” in the header.
 *
 * @return string|null Absolute path, or null if nothing usable exists.
 */
function kecktech_branding_display_path(): ?string
{
    $dir = WP_CONTENT_DIR . '/uploads/kecktech/';
    $candidates = array(
        KECKTECH_BRAND_BASENAME,
        'transparent-logo-768x768.png',
        'transparent-logo-300x300.png',
        'transparent-logo-150x150.png',
    );
    foreach ($candidates as $name) {
        $p = $dir . $name;
        if (file_exists($p) && filesize($p) > 0) {
            return $p;
        }
    }
    return null;
}

/**
 * True if the read-only mount has the asset (bootstrap can run) or any display file already exists.
 */
function kecktech_branding_usable(): bool
{
    if (file_exists(kecktech_brand_source_path())) {
        return true;
    }
    return kecktech_branding_display_path() !== null;
}

/**
 * Public URL for the PNG the browser should load (prefers full file, else largest derivative).
 */
function kecktech_branding_file_url(): string
{
    $path = kecktech_branding_display_path();
    if ($path === null) {
        return '';
    }
    $upload_dir = wp_upload_dir();
    if (!empty($upload_dir['error'])) {
        return '';
    }
    $url = trailingslashit($upload_dir['baseurl']) . 'kecktech/' . basename($path);
    $fixed = kecktech_force_https_url($url);
    return is_string($fixed) ? $fixed : $url;
}

/**
 * Writable path to footer white wordmark under uploads/kecktech/.
 */
function kecktech_footer_logo_file_path(): string
{
    return WP_CONTENT_DIR . '/uploads/kecktech/' . KECKTECH_FOOTER_BRAND_BASENAME;
}

/**
 * Public URL for footer wordmark (empty if file missing).
 */
function kecktech_footer_logo_url(): string
{
    $path = kecktech_footer_logo_file_path();
    if (!file_exists($path) || filesize($path) === 0) {
        return '';
    }
    $upload_dir = wp_upload_dir();
    if (!empty($upload_dir['error'])) {
        return '';
    }
    $url = trailingslashit($upload_dir['baseurl']) . 'kecktech/' . KECKTECH_FOOTER_BRAND_BASENAME;
    $fixed = kecktech_force_https_url($url);
    return is_string($fixed) ? $fixed : $url;
}

/**
 * Show white transparent wordmark instead of plain “Kecktech” text in the footer (Astra + block Site Title).
 */
function kecktech_footer_wordmark_styles(): void
{
    if (is_admin()) {
        return;
    }
    $url = kecktech_footer_logo_url();
    if ($url === '') {
        return;
    }
    $u = esc_url($url);
    echo '<style id="kecktech-footer-wordmark">'
        . '.site-footer .ast-footer-site-title,'
        . '.site-below-footer-wrap .ast-footer-site-title,'
        . '.ast-footer-wrap .ast-footer-site-title,'
        . 'footer.site-footer .wp-block-site-title a{'
        . 'display:inline-block!important;font-size:0!important;line-height:0!important;'
        . 'color:transparent!important;text-shadow:none!important;overflow:hidden;vertical-align:middle;'
        . 'min-height:40px!important;max-height:48px!important;min-width:120px!important;'
        . 'max-width:min(240px,55vw)!important;'
        . 'background:url(\'' . esc_attr($u) . '\') no-repeat left center / contain!important;'
        . '}'
        . '</style>';
}

/**
 * Preserve site name for assistive tech (visible text is replaced by background image).
 */
function kecktech_footer_wordmark_a11y_script(): void
{
    if (is_admin()) {
        return;
    }
    if (kecktech_footer_logo_url() === '') {
        return;
    }
    $name = wp_json_encode(get_bloginfo('name', 'display'));
    echo '<script id="kecktech-footer-wordmark-a11y">(function(){var n=' . $name . ';document.querySelectorAll(".site-footer .ast-footer-site-title,.site-below-footer-wrap .ast-footer-site-title,.ast-footer-wrap .ast-footer-site-title,footer.site-footer .wp-block-site-title a").forEach(function(el){if(el&&!el.getAttribute("aria-label")){el.setAttribute("aria-label",n);}});})();</script>' . "\n";
}

add_action('wp_head', 'kecktech_footer_wordmark_styles', 101);
add_action('wp_footer', 'kecktech_footer_wordmark_a11y_script', 99);

/**
 * Raw <img> tag pointing at the static uploads file.
 */
function kecktech_build_static_logo_img(): string
{
    $url = kecktech_branding_file_url();
    if ($url === '') {
        return '';
    }
    $path = kecktech_branding_display_path();
    $w    = 512;
    $h    = 512;
    if ($path && is_string($path)) {
        $dims = @getimagesize($path);
        if (is_array($dims) && isset($dims[0], $dims[1])) {
            $w = (int) $dims[0];
            $h = (int) $dims[1];
        }
    }
    return sprintf(
        '<img src="%s" class="custom-logo" alt="%s" width="%d" height="%d" decoding="async" loading="eager" fetchpriority="high" onerror="this.setAttribute(\'data-kecktech-broken\',\'1\');this.style.visibility=\'hidden\';" />',
        esc_url($url),
        esc_attr(get_bloginfo('name', 'display')),
        $w,
        $h
    );
}

/**
 * Constrain header logo dimensions (1024×1024 uploads read as a huge square without this).
 * Covers Astra, custom_logo, and core Site Logo block.
 */
function kecktech_logo_header_styles(): void
{
    echo '<style id="kecktech-logo-header-css">'
        . '.site-header .custom-logo-link img,.site-header .custom-logo-link picture img,'
        . '.ast-primary-header .custom-logo,.ast-header-custom-item img.custom-logo,'
        . '.custom-logo-link img.custom-logo,.wp-block-site-logo img,.wp-block-site-logo a img,'
        . 'header .site-logo img{'
        . 'max-height:72px!important;width:auto!important;height:auto!important;'
        . 'object-fit:contain;background:transparent!important;'
        . '}'
        . '.custom-logo-link,.wp-block-site-logo a{display:inline-flex!important;align-items:center;line-height:0;}'
        . '.site-logo-img,.site-logo-img a,.ast-site-identity .site-logo-img{'
        . 'background-color:transparent!important;'
        . '}'
        . '</style>';
}

/**
 * If the <img> fails (404), show the same asset as a background on the link (Astra title/tagline column).
 */
function kecktech_logo_fallback_background_css(): void
{
    if (is_admin()) {
        return;
    }
    $url = kecktech_branding_file_url();
    if ($url === '') {
        return;
    }
    $u = esc_url($url);
    echo '<style id="kecktech-logo-bg-fallback">'
        . ':root{--kecktech-logo-url:url(\'' . esc_attr($u) . '\');}'
        . '#masthead .ast-builder-layout-element[data-section="title_tagline"] .custom-logo-link,'
        . '.ast-primary-header .ast-builder-layout-element[data-section="title_tagline"] .custom-logo-link,'
        . '#masthead .site-logo-img .custom-logo-link,.ast-primary-header .site-logo-img .custom-logo-link,'
        . 'header.site-header .site-branding .custom-logo-link,.site-header .custom-logo-link{'
        . 'background-image:var(--kecktech-logo-url)!important;background-size:contain!important;'
        . 'background-repeat:no-repeat!important;background-position:left center!important;'
        . 'min-width:min(180px,40vw)!important;min-height:48px!important;'
        . '}'
        . '.site-header .custom-logo-link img[data-kecktech-broken="1"],'
        . '#masthead .custom-logo-link img[data-kecktech-broken="1"],'
        . '.ast-primary-header .custom-logo-link img[data-kecktech-broken="1"]{display:none!important;}'
        . '</style>';
}

add_action('wp_head', 'kecktech_logo_header_styles', 99);
add_action('wp_head', 'kecktech_logo_fallback_background_css', 98);

add_filter('wp_get_attachment_url', 'kecktech_force_https_url', 99);
add_filter('wp_get_attachment_image_src', function ($image, $attachment_id, $size, $icon) {
    if (!is_array($image) || empty($image[0])) {
        return $image;
    }
    $image[0] = kecktech_force_https_url($image[0]);
    return $image;
}, 99, 4);

add_filter('wp_calculate_image_srcset', function ($sources) {
    if (!is_array($sources)) {
        return $sources;
    }
    foreach ($sources as $w => $data) {
        if (!empty($data['url'])) {
            $sources[$w]['url'] = kecktech_force_https_url($data['url']);
        }
    }
    return $sources;
}, 99);

add_filter('upload_dir', function ($dirs) {
    if (!is_array($dirs)) {
        return $dirs;
    }
    if (function_exists('is_ssl') && is_ssl()) {
        $dirs['url']     = kecktech_force_https_url($dirs['url']);
        $dirs['baseurl'] = kecktech_force_https_url($dirs['baseurl']);
    }
    return $dirs;
}, 99);

/**
 * Rebuild custom logo markup so img/src/srcset use corrected URLs (avoids empty or blocked loads).
 *
 * @param string $html
 * @param int    $blog_id
 */
function kecktech_filter_custom_logo_html($html, $blog_id): string
{
    $static = kecktech_build_static_logo_img();
    if ($static !== '') {
        return sprintf(
            '<a href="%s" class="custom-logo-link" rel="home" itemprop="url">%s</a>',
            esc_url(home_url('/')),
            $static
        );
    }

    $logo_id = (int) get_theme_mod('custom_logo');
    if ($logo_id <= 0) {
        return $html;
    }
    if (! wp_attachment_is_image($logo_id)) {
        return $html;
    }
    $path = get_attached_file($logo_id);
    if (! $path || ! file_exists($path)) {
        return $html;
    }
    $img = wp_get_attachment_image(
        $logo_id,
        'full',
        false,
        array(
            'class' => 'custom-logo',
            'alt'   => get_bloginfo('name', 'display'),
        )
    );
    if ($img === '') {
        return $html;
    }
    return sprintf(
        '<a href="%s" class="custom-logo-link" rel="home" itemprop="url">%s</a>',
        esc_url(home_url('/')),
        $img
    );
}

add_filter('get_custom_logo', 'kecktech_filter_custom_logo_html', 99, 2);

/**
 * Astra only calls get_custom_logo() when astra_has_custom_logo is true (defaults to has_custom_logo()).
 * If theme_mod is missing or points at a dead attachment, has_custom_logo() is false — our get_custom_logo
 * filter never runs and the header can show an empty / placeholder “logo” block (often a solid color).
 */
function kecktech_astra_should_show_logo(bool $has): bool
{
    if ($has) {
        return true;
    }
    return kecktech_branding_usable();
}

add_filter('astra_has_custom_logo', 'kecktech_astra_should_show_logo', 20);

/**
 * Belt-and-suspenders: if anything left site-logo-img empty, inject static markup.
 *
 * @param string $html
 */
function kecktech_astra_logo_markup(string $html, $display_site_title = null, $display_site_tagline = null): string
{
    unset($display_site_title, $display_site_tagline);
    $inner = kecktech_build_static_logo_inner_markup();
    if ($inner === '') {
        return $html;
    }
    // Empty wrapper (whitespace-only between tags).
    if (preg_match('#<span[^>]*\bsite-logo-img\b[^>]*>\s*</span>#i', $html)) {
        $replaced = preg_replace(
            '#(<span[^>]*\bsite-logo-img\b[^>]*>)\s*(</span>)#i',
            '$1' . $inner . '$2',
            $html,
            1
        );
        return is_string($replaced) ? $replaced : $html;
    }
    return $html;
}

/**
 * Inner logo markup only (no outer span) for astra_logo injection.
 */
function kecktech_build_static_logo_inner_markup(): string
{
    $static = kecktech_build_static_logo_img();
    if ($static === '') {
        return '';
    }
    return sprintf(
        '<a href="%s" class="custom-logo-link" rel="home" itemprop="url">%s</a>',
        esc_url(home_url('/')),
        $static
    );
}

add_filter('astra_logo', 'kecktech_astra_logo_markup', 25, 3);

/**
 * Site Logo block can bypass get_custom_logo; rebuild when it uses the same theme mod.
 *
 * @param array<string,mixed> $block
 */
function kecktech_render_site_logo_block(string $content, array $block): string
{
    if (($block['blockName'] ?? '') !== 'core/site-logo') {
        return $content;
    }
    $static = kecktech_build_static_logo_img();
    if ($static !== '') {
        $img = str_replace('class="custom-logo"', 'class="custom-logo wp-block-site-logo__image"', $static);
    } else {
        $logo_id = (int) get_theme_mod('custom_logo');
        if ($logo_id <= 0 || ! wp_attachment_is_image($logo_id)) {
            return $content;
        }
        $path = get_attached_file($logo_id);
        if (! $path || ! file_exists($path)) {
            return $content;
        }
        $img = wp_get_attachment_image(
            $logo_id,
            'full',
            false,
            array(
                'class' => 'custom-logo wp-block-site-logo__image',
                'alt'   => get_bloginfo('name', 'display'),
            )
        );
        if ($img === '') {
            return $content;
        }
    }
    $inner = sprintf(
        '<a href="%s" class="custom-logo-link" rel="home">%s</a>',
        esc_url(home_url('/')),
        $img
    );
    $replaced = preg_replace(
        '#(<div[^>]*\bwp-block-site-logo\b[^>]*>).*(</div>\s*)$#s',
        '$1' . $inner . '$2',
        $content,
        1,
        $count
    );
    return ($count > 0 && is_string($replaced)) ? $replaced : $content;
}

add_filter('render_block', 'kecktech_render_site_logo_block', 20, 2);

// ── Header CTA: Request Quote → Customer Login (portal URL later via filter) ─────────────────

/**
 * Default `#`; override with: add_filter( 'kecktech_customer_portal_url', fn() => 'https://...' );
 */
function kecktech_customer_portal_url(): string
{
    $url = apply_filters('kecktech_customer_portal_url', '#');
    return is_string($url) ? $url : '#';
}

/**
 * @param string              $content
 * @param array<string,mixed> $block
 */
function kecktech_replace_header_quote_cta(string $content, array $block): string
{
    $needles = array('REQUEST QUOTE', 'Request Quote', 'Request a quote', 'REQUEST A QUOTE');
    $hit     = false;
    foreach ($needles as $n) {
        if (stripos($content, $n) !== false) {
            $hit = true;
            break;
        }
    }
    if (! $hit) {
        return $content;
    }
    foreach ($needles as $n) {
        $content = str_ireplace($n, 'Customer Login', $content);
    }
    $url     = kecktech_customer_portal_url();

    if (class_exists('DOMDocument')) {
        libxml_use_internal_errors(true);
        $dom = new DOMDocument();
        $dom->loadHTML(
            '<?xml encoding="UTF-8">' . $content,
            LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD
        );
        foreach ($dom->getElementsByTagName('a') as $a) {
            $text = trim(preg_replace('/\s+/', ' ', $a->textContent));
            if ($text === 'Customer Login' || str_contains($text, 'Customer Login')) {
                $href = ($url === '#' || $url === '') ? '#' : esc_url($url);
                $a->setAttribute('href', $href);
                if ($href === '#') {
                    $a->setAttribute('aria-disabled', 'true');
                }
            }
        }
        $out = $dom->saveHTML();
        libxml_clear_errors();
        if (is_string($out) && $out !== '') {
            return $out;
        }
    }

    return $content;
}

add_filter('render_block', 'kecktech_replace_header_quote_cta', 25, 2);

// ── Extra selectors (Astra header builder / Spectra) ─────────────────────────────────────────

/**
 * @return void
 */
function kecktech_logo_header_styles_v2(): void
{
    echo '<style id="kecktech-logo-header-css-2">'
        . '.ast-site-identity-img,.site-header .site-branding img,.ast-header-break-point .site-branding img,'
        . '.ast-builder-layout-element img.custom-logo,.ast-builder-layout-element .site-logo-img img,'
        . 'header img.custom-logo,header .wp-block-site-logo img{'
        . 'max-height:72px!important;width:auto!important;height:auto!important;object-fit:contain;'
        . 'background:transparent!important;'
        . '}'
        . '.ast-builder-layout-element .site-logo-img a,.ast-site-identity .site-logo-img{line-height:0;display:inline-flex;}'
        . '</style>';
}

add_action('wp_head', 'kecktech_logo_header_styles_v2', 100);

/**
 * Last-resort: repair broken header <img> src / empty logo anchors (Astra builder, lazy, bad DB URLs).
 */
function kecktech_logo_footer_script(): void
{
    if (is_admin() || kecktech_branding_display_path() === null) {
        return;
    }
    $u   = wp_json_encode(kecktech_branding_file_url());
    $alt = wp_json_encode(get_bloginfo('name', 'display'));
    echo '<script id="kecktech-logo-fallback">(function(){var u=' . $u . ',alt=' . $alt . ';function fixImg(img){if(!img||img.tagName!=="IMG"||!u)return;if(img.naturalWidth>8)return;img.removeAttribute("srcset");img.removeAttribute("sizes");img.src=u;img.alt=alt;}function patch(){var sels=["header img.custom-logo",".ast-primary-header img.custom-logo",".ast-builder-layout-element .site-logo-img img",".wp-block-site-logo img",".site-header img.custom-logo","#masthead img.custom-logo","#masthead .site-logo-img img","#masthead .custom-logo-link img","#masthead .site-branding img",".ast-primary-header .site-logo-img img",".ast-primary-header .custom-logo-link img"];sels.forEach(function(sel){try{document.querySelectorAll(sel).forEach(fixImg);}catch(e){}});document.querySelectorAll(".ast-site-identity .site-logo-img a,.ast-builder-layout-element .site-logo-img a,header .site-branding .custom-logo-link").forEach(function(a){if(a.querySelector("img"))return;var i=document.createElement("img");i.src=u;i.className="custom-logo";i.alt=alt;i.style.maxHeight="72px";i.style.width="auto";a.appendChild(i);});}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",patch);else patch();window.addEventListener("load",patch);})();</script>' . "\n";
}

add_action('wp_footer', 'kecktech_logo_footer_script', 5);
